### ISSUE TITLE
how to conveniently print all aliases with their definitions in PowerShell?

### ISSUE THREAD

**Issue by badgh** [gluons/powershell-git-aliases#14]
In git itself it is possible to print all aliases (which are located in .gitconfig) with one command, like `git config --get-regexp alias`. This prints the names of all aliases, and their definitions. Is it possible to do the same in PowerShell?

So far, I managed to print all aliases with the command: `Get-Command -Module git-aliases | Select-Object Name, ScriptBlock | Format-List`. But the output is kinda ugly...

**Comment by gluons** [comment]
New command (`Get-Git-Aliases`) has been released in new version.
