### ISSUE TITLE
Add git push --force-with-lease

### ISSUE THREAD

**Issue by fabiosangregorio** [gluons/powershell-git-aliases#17]
Hi, awesome repo :)

It would be awesome if we could have a `git push --force-with-lease` alias, maybe as `gpfl` or something like that. What do you think?

**Comment by gluons** [comment]
I'll add `gpf` following [Oh My Zsh's git plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git)

**Comment by fabiosangregorio** [comment]
Oh right, it should be `ggf` for `git push --force origin $(current_branch)` and `ggfl` for `git push --force-with-lease origin $(current_branch)` then.

**Comment by gluons** [comment]
Released with v0.2.2.
