### ISSUE TITLE
Default branch used to be 'master' but now becomes 'main'

### ISSUE THREAD

**Issue by JohannesEH** [gluons/powershell-git-aliases#21]
Make `gcm` and similar 'master' oriented commands configurable and/or check for 'main'/'master' branches and select correct branch accordingly. The default should probably be 'main' as this is the new default branch name on a lot of git hosts like [GitHub](https://github.com/github/renaming), [Bitbucket](https://bitbucket.org/blog/moving-away-from-master-as-the-default-name-for-branches-in-git), [Azure DevOps](https://devblogs.microsoft.com/devops/azure-repos-default-branch-name/), to mention a few.

Finally i just wanted to say thanks for these aliases. I'm using them every day. :)

**Comment by JohannesEH** [comment]
I can see in oh-my-zsh that they make this configurable by checking using a [function](https://github.com/ohmyzsh/ohmyzsh/blob/f21e646ce6c09198f7f625c597f08af49551fdb0/plugins/git/git.plugin.zsh#L33) `git_main_branch` which checks for existence of branches 'main' and 'trunk' in that order and outputs the first one it finds, or if outputs 'master' if none is found.

**Comment by gluons** [comment]
Done. Released in v0.3.0. 😃

**Comment by JohannesEH** [comment]
Nice! Didn't see that you fixed this. Thank you! 👍❤️

**Comment by gluons** [comment]
> 
> 
> Note: De to a bug in PowerShell Core 7.1 the current Get-Git-MainBranch implementation wont work. We can fix it by chaging the `$?` checks with `$LASTEXITCODE` checks. See PR #25

Done. Released.
