### ISSUE TITLE
Remove sign flag from gcan!

### ISSUE THREAD

**Issue by sergiohgz** [gluons/powershell-git-aliases#23]
Hello,

As you can see in [Oh-My-ZSH Git plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git#aliases), command `gcan!` don't force commit sign flag (`-s`). Instead, they have another command (`gcans!`).

I can try to create a PR removing this flag from `gcan!` and adding `gcans!` command if you want.

Thanks for this awesome plugin 😍

**Comment by gluons** [comment]
Released with v0.3.1.
