### ISSUE TITLE
 Remove-Alias gcb -Force cannot find matching alias as alias 'gcb' does not exist.

### ISSUE THREAD

**Issue by xeoneux** [gluons/powershell-git-aliases#28]
I'm getting this when I add `Import-Module git-aliases -DisableNameChecking`:
```pwsh
Remove-Alias: C:\Users\xeoneux\Documents\PowerShell\Modules\git-aliases\0.3.3\aliases.ps1:5
Line |
   5 |  Remove-Alias gcb -Force
     |  ~~~~~~~~~~~~~~~~~~~~~~~
     | This command cannot find a matching alias because an alias with the name 'gcb' does not exist.
```

**Comment by gluons** [comment]
What's your PowerShell version?  
You can check it via `$PSVersionTable` variable.

**Comment by xeoneux** [comment]
v7.1.3

**Comment by gluons** [comment]
Weird. I'm using with v7.1.3 too.  
I cannot reproduce.

**Comment by gluons** [comment]
v0.3.4 released.  
Hope it helps.

**Comment by xeoneux** [comment]
Thanks! @gluons

**Comment by xeoneux** [comment]
Switching to Windows after years on oh-my-zsh on Linux, all these git shortcuts are muscle memory now :smile: 
Thanks for the module!
